# Generated by Django 3.1 on 2020-08-18 02:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vinhos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomeVinho', models.CharField(max_length=200)),
                ('imagemVinho', models.ImageField(upload_to='.')),
                ('descVinho', models.TextField()),
                ('dataCadastro', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
    ]
