# Generated by Django 3.1 on 2020-08-20 00:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vinhos', '0002_auto_20200819_2056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vinhos',
            name='data_cadastro',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 8, 19, 21, 25, 1, 864930)),
        ),
    ]
