# Generated by Django 3.1 on 2020-08-26 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vinhos', '0006_auto_20200821_2335'),
    ]

    operations = [
        migrations.AddField(
            model_name='vinhos',
            name='refrigerado',
            field=models.BooleanField(default=False),
        ),
    ]
