# Generated by Django 3.1 on 2020-08-26 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vinhos', '0007_vinhos_refrigerado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vinhos',
            name='imagem_vinho',
            field=models.ImageField(blank=True, upload_to='.'),
        ),
    ]
