# Generated by Django 3.1 on 2020-08-26 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vinhos', '0008_auto_20200825_2231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vinhos',
            name='imagem_vinho',
            field=models.ImageField(blank=True, upload_to='bottles/%d/%m/%Y'),
        ),
    ]
