# Generated by Django 3.1 on 2020-09-05 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vinhos', '0010_auto_20200825_2238'),
    ]

    operations = [
        migrations.AddField(
            model_name='vinhos',
            name='preco_vinho',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
            preserve_default=False,
        ),
    ]
